export const CREATE_AREA_STARTED = 'CREATE_AREA_STARTED';
export const CREATE_AREA_SUCCESS = 'CREATE_AREA_SUCCESS';
export const CREATE_AREA_FAILED = 'CREATE_AREA_FAILED';

export const DEFAULT_STATUS = 'DEFAULT_STATUS';